export type PlatformType =
  | 'youtube'
  | 'tiktok'
  | 'facebook'
  | 'twitter'
  | 'bilibili'
  | 'instagram'
  | 'vimeo'
  | 'twitch'
  | 'custom';

export interface MediaFormatOption {
  formatId: string;
  extension: string;
  resolution: string; // e.g. "3840x2160 (4K)", "1920x1080 (1080p)"
  height: number;
  filesizeApproxBytes?: number;
  vcodec: string;
  acodec: string;
  fps?: number;
  note?: string;
  isVideo: boolean;
  isAudio: boolean;
}

export interface SubtitleTrackOption {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
  ext: string;
}

export interface MediaUrlInfo {
  url: string;
  platform: PlatformType;
  title: string;
  description: string;
  uploader: string;
  uploaderId?: string;
  durationSeconds: number;
  thumbnailUrl?: string;
  formats: MediaFormatOption[];
  subtitles: SubtitleTrackOption[];
}

export type DownloadJobStatus =
  | 'queued'
  | 'analyzing'
  | 'downloading'
  | 'paused'
  | 'completed'
  | 'failed'
  | 'cancelled';

export interface DownloadJob {
  id: string;
  url: string;
  platform: PlatformType;
  title: string;
  uploader: string;
  thumbnailUrl?: string;
  selectedFormatId: string;
  selectedResolution: string;
  includeSubtitles: boolean;
  subtitleLangs?: string[];
  includeThumbnail: boolean;
  audioOnly: boolean;
  outputDirectory: string;
  outputFilePath?: string;
  
  status: DownloadJobStatus;
  progressPercent: number;
  speedBytesPerSec: number;
  etaSeconds: number;
  downloadedBytes: number;
  totalBytes: number;
  errorMessage?: string;
  
  createdAt: string;
  completedAt?: string;
}

export interface DownloadProgress {
  jobId: string;
  progressPercent: number;
  speedBytesPerSec: number;
  etaSeconds: number;
  downloadedBytes: number;
  totalBytes: number;
  status: DownloadJobStatus;
}
