import { ProjectData } from '../types/project';

export const FALLBACK_SAMPLE_PROJECT: ProjectData = {
  id: 'sample-cyberpunk-doc',
  name: 'Cyberpunk 2077: Night City Secrets',
  description: 'Deep dive documentary into future tech, mega-corporations, and synthetic intelligence in Night City.',
  version: '1.0.0',
  createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  updatedAt: new Date(Date.now() - 3600000).toISOString(),
  lastOpenedAt: new Date().toISOString(),
  status: 'translated',
  progressPercent: 70,
  projectDirectory: 'C:\\Users\\sakpo\\AppData\\Roaming\\MediaForgeAI\\Projects\\sample-cyberpunk-doc',
  sourceLanguage: 'en',
  targetLanguage: 'km',
  secondaryTargetLanguages: ['ja', 'zh'],
  sourceMedia: {
    type: 'file',
    pathOrUrl: 'C:\\Videos\\cyberpunk_secrets_4k.mp4',
    filename: 'cyberpunk_secrets_4k.mp4',
    durationSeconds: 142.5,
    resolution: { width: 3840, height: 2160 },
    fps: 60,
    fileSizeBytes: 148592000,
    codec: 'hevc',
    audioSampleRate: 48000,
    audioChannels: 2,
    platform: 'youtube',
  },
  speakers: [
    {
      id: 'spk-narrator',
      name: 'Johnny Silverhand (Narrator)',
      color: '#00f0ff',
      gender: 'male',
      assignedVoiceId: 'km-KH-PisethNeural',
      voiceProvider: 'edge-tts',
      pitchMultiplier: 0.95,
      rateMultiplier: 1.0,
      volumeMultiplier: 1.0,
    },
    {
      id: 'spk-alt',
      name: 'Alt Cunningham',
      color: '#8b5cf6',
      gender: 'female',
      assignedVoiceId: 'km-KH-SreymomNeural',
      voiceProvider: 'edge-tts',
      pitchMultiplier: 1.05,
      rateMultiplier: 0.95,
      volumeMultiplier: 0.9,
    },
  ],
  segments: [
    {
      id: 'seg-1',
      start: 0.0,
      end: 4.8,
      speakerId: 'spk-narrator',
      speakerName: 'Johnny Silverhand (Narrator)',
      originalText: 'Night City wasn\'t built on dreams. It was built on neon, chrome, and broken promises.',
      translatedText: 'ទីក្រុង Night City មិនត្រូវបានសាងសង់ឡើងលើក្តីស្រមៃនោះទេ។ វាត្រូវបានសាងសង់ឡើងលើពន្លឺនេអុង ដែកក្រូម និងការសន្យាមិនពិត។',
      confidence: 0.98,
    },
    {
      id: 'seg-2',
      start: 5.2,
      end: 9.6,
      speakerId: 'spk-narrator',
      speakerName: 'Johnny Silverhand (Narrator)',
      originalText: 'Every megacorp here owns a piece of your soul before you even wake up in the morning.',
      translatedText: 'ក្រុមហ៊ុនយក្សនីមួយៗនៅទីនេះគ្រប់គ្រងព្រលឹងរបស់អ្នក មុនពេលអ្នកភ្ញាក់ពីដំណេកនៅពេលព្រឹកទៅទៀត។',
      confidence: 0.96,
    },
    {
      id: 'seg-3',
      start: 10.1,
      end: 15.4,
      speakerId: 'spk-alt',
      speakerName: 'Alt Cunningham',
      originalText: 'The Blackwall is failing, Johnny. Beyond that barrier lies something far worse than Arasaka.',
      translatedText: 'ជញ្ជាំងខ្មៅ Blackwall កំពុងបរាជ័យហើយ Johnny។ ហួសពីរបាំងនោះ គឺមានអ្វីមួយដ៏អាក្រក់ជាង Arasaka ទៅទៀត។',
      confidence: 0.97,
    },
    {
      id: 'seg-4',
      start: 16.0,
      end: 21.3,
      speakerId: 'spk-narrator',
      speakerName: 'Johnny Silverhand (Narrator)',
      originalText: 'Then let\'s burn it all down together. One last time.',
      translatedText: 'អញ្ចឹងតោះយើងដុតកម្ទេចវាចោលទាំងអស់គ្នា។ សម្រាប់លើកចុងក្រោយ។',
      confidence: 0.99,
    },
  ],
  stems: {
    isSeparated: true,
    vocalVolume: 0.1,
    musicVolume: 0.85,
    sfxVolume: 0.9,
    dubbedVolume: 1.0,
  },
  subtitleStyle: {
    fontFamily: 'Outfit',
    fontSize: 26,
    primaryColor: '#00f0ff',
    outlineColor: '#0c0e14',
    outlineWidth: 4,
    shadowColor: 'rgba(0, 240, 255, 0.4)',
    shadowBlur: 12,
    position: 'bottom',
    marginVertical: 45,
    alignment: 'center',
    bold: true,
    italic: false,
  },
  exportSettings: {
    format: 'mp4',
    resolutionPreset: '4k',
    videoCodec: 'auto',
    crf: 18,
    bitrateKbps: 18000,
    hardwareAcceleration: true,
    burnInSubtitles: false,
    includeDubbedAudio: true,
    outputPath: '',
  },
  tags: ['Gaming', 'Cyberpunk', 'Khmer Dubbing', '4K HDR'],
  notes: 'Demo project highlighting multi-speaker diarization and English to Khmer video translation.',
};
