import React, { createContext, useContext, useEffect, useState } from 'react';
import {
  MediaUrlInfo,
  DownloadJob,
  DownloadProgress,
  PlatformType,
} from '../types/downloader';

interface DownloaderContextType {
  queue: DownloadJob[];
  analyzedMedia: MediaUrlInfo | null;
  isAnalyzing: boolean;
  error: string | null;
  analyzeUrl: (url: string) => Promise<MediaUrlInfo | null>;
  clearAnalyzed: () => void;
  addJob: (options: Partial<DownloadJob>) => Promise<DownloadJob | null>;
  addBulkJobs: (urls: string[]) => Promise<DownloadJob[]>;
  pauseJob: (id: string) => Promise<boolean>;
  resumeJob: (id: string) => Promise<boolean>;
  cancelJob: (id: string) => Promise<boolean>;
  retryJob: (id: string) => Promise<boolean>;
  clearCompleted: () => Promise<boolean>;
  refreshQueue: () => Promise<void>;
  detectPlatform: (url: string) => PlatformType;
}

const DownloaderContext = createContext<DownloaderContextType>({
  queue: [],
  analyzedMedia: null,
  isAnalyzing: false,
  error: null,
  analyzeUrl: async () => null,
  clearAnalyzed: () => {},
  addJob: async () => null,
  addBulkJobs: async () => [],
  pauseJob: async () => false,
  resumeJob: async () => false,
  cancelJob: async () => false,
  retryJob: async () => false,
  clearCompleted: async () => false,
  refreshQueue: async () => {},
  detectPlatform: () => 'custom',
});

export const DownloaderProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [queue, setQueue] = useState<DownloadJob[]>([]);
  const [analyzedMedia, setAnalyzedMedia] = useState<MediaUrlInfo | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const detectPlatform = (url: string): PlatformType => {
    if (!url) return 'custom';
    if (/(?:youtube\.com|youtu\.be)/i.test(url)) return 'youtube';
    if (/tiktok\.com/i.test(url)) return 'tiktok';
    if (/(?:facebook\.com|fb\.watch)/i.test(url)) return 'facebook';
    if (/(?:twitter\.com|x\.com)/i.test(url)) return 'twitter';
    if (/bilibili\.com/i.test(url)) return 'bilibili';
    if (/instagram\.com/i.test(url)) return 'instagram';
    if (/vimeo\.com/i.test(url)) return 'vimeo';
    if (/twitch\.tv/i.test(url)) return 'twitch';
    return 'custom';
  };

  const refreshQueue = async () => {
    if (window.electronAPI?.downloaderGetQueue) {
      try {
        const list = await window.electronAPI.downloaderGetQueue();
        setQueue(list);
      } catch (err) {
        console.error('Failed to get download queue:', err);
      }
    }
  };

  const analyzeUrl = async (url: string): Promise<MediaUrlInfo | null> => {
    setIsAnalyzing(true);
    setError(null);
    if (window.electronAPI?.downloaderAnalyzeUrl) {
      try {
        const info = await window.electronAPI.downloaderAnalyzeUrl(url);
        setAnalyzedMedia(info);
        setIsAnalyzing(false);
        return info;
      } catch (err: any) {
        setError(err?.message || 'Failed to inspect media URL');
        setIsAnalyzing(false);
        return null;
      }
    } else {
      // Mock fallback for preview
      const platform = detectPlatform(url);
      const mock: MediaUrlInfo = {
        url,
        platform,
        title: 'Documentary: Next Generation Autonomous AI Engines (8K Demo)',
        description: 'Demonstrating machine intelligence and high-throughput multi-modal computing.',
        uploader: 'DeepMind Tech Labs',
        uploaderId: 'deepmind_labs',
        durationSeconds: 245,
        thumbnailUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        formats: [
          {
            formatId: '313',
            extension: 'mp4',
            resolution: '4K (2160p)',
            height: 2160,
            filesizeApproxBytes: 485000000,
            vcodec: 'vp9',
            acodec: 'opus',
            fps: 60,
            isVideo: true,
            isAudio: true,
          },
          {
            formatId: '137',
            extension: 'mp4',
            resolution: 'Full HD (1080p)',
            height: 1080,
            filesizeApproxBytes: 125000000,
            vcodec: 'h264',
            acodec: 'aac',
            fps: 60,
            isVideo: true,
            isAudio: true,
          },
          {
            formatId: '140',
            extension: 'm4a',
            resolution: 'Audio Only',
            height: 0,
            filesizeApproxBytes: 18000000,
            vcodec: 'none',
            acodec: 'aac',
            isVideo: false,
            isAudio: true,
          },
        ],
        subtitles: [
          { languageCode: 'en', languageName: 'ENGLISH', isAutoGenerated: false, ext: 'srt' },
          { languageCode: 'km', languageName: 'KHMER (Auto)', isAutoGenerated: true, ext: 'vtt' },
        ],
      };
      setAnalyzedMedia(mock);
      setIsAnalyzing(false);
      return mock;
    }
  };

  const clearAnalyzed = () => {
    setAnalyzedMedia(null);
    setError(null);
  };

  const addJob = async (options: Partial<DownloadJob>): Promise<DownloadJob | null> => {
    if (window.electronAPI?.downloaderAddJob) {
      try {
        const job = await window.electronAPI.downloaderAddJob(options);
        await refreshQueue();
        return job;
      } catch (err: any) {
        setError(err?.message || 'Failed to add job');
        return null;
      }
    } else {
      const mockJob: DownloadJob = {
        id: 'job-' + Date.now(),
        url: options.url || '',
        platform: options.platform || 'custom',
        title: options.title || 'Media Download',
        uploader: options.uploader || 'Creator',
        selectedFormatId: options.selectedFormatId || 'best',
        selectedResolution: options.selectedResolution || '1080p',
        includeSubtitles: options.includeSubtitles || true,
        includeThumbnail: options.includeThumbnail || true,
        audioOnly: options.audioOnly || false,
        outputDirectory: 'C:\\Downloads',
        status: 'downloading',
        progressPercent: 45.2,
        speedBytesPerSec: 8.5 * 1024 * 1024,
        etaSeconds: 14,
        downloadedBytes: 52 * 1024 * 1024,
        totalBytes: 120 * 1024 * 1024,
        createdAt: new Date().toISOString(),
      };
      setQueue((prev) => [mockJob, ...prev]);
      return mockJob;
    }
  };

  const addBulkJobs = async (urls: string[]): Promise<DownloadJob[]> => {
    if (window.electronAPI?.downloaderAddBulkJobs) {
      try {
        const jobs = await window.electronAPI.downloaderAddBulkJobs(urls);
        await refreshQueue();
        return jobs;
      } catch (err) {
        console.error('Failed to add bulk jobs:', err);
        return [];
      }
    }
    return [];
  };

  const pauseJob = async (id: string): Promise<boolean> => {
    if (window.electronAPI?.downloaderPauseJob) {
      const res = await window.electronAPI.downloaderPauseJob(id);
      await refreshQueue();
      return res;
    }
    return false;
  };

  const resumeJob = async (id: string): Promise<boolean> => {
    if (window.electronAPI?.downloaderResumeJob) {
      const res = await window.electronAPI.downloaderResumeJob(id);
      await refreshQueue();
      return res;
    }
    return false;
  };

  const cancelJob = async (id: string): Promise<boolean> => {
    if (window.electronAPI?.downloaderCancelJob) {
      const res = await window.electronAPI.downloaderCancelJob(id);
      await refreshQueue();
      return res;
    }
    return false;
  };

  const retryJob = async (id: string): Promise<boolean> => {
    if (window.electronAPI?.downloaderRetryJob) {
      const res = await window.electronAPI.downloaderRetryJob(id);
      await refreshQueue();
      return res;
    }
    return false;
  };

  const clearCompleted = async (): Promise<boolean> => {
    if (window.electronAPI?.downloaderClearCompleted) {
      const res = await window.electronAPI.downloaderClearCompleted();
      await refreshQueue();
      return res;
    } else {
      setQueue((prev) => prev.filter((j) => j.status !== 'completed' && j.status !== 'cancelled'));
      return true;
    }
  };

  useEffect(() => {
    refreshQueue();

    let unsubProgress: (() => void) | undefined;
    if (window.electronAPI?.onDownloadProgress) {
      unsubProgress = window.electronAPI.onDownloadProgress((prog: DownloadProgress) => {
        setQueue((prev) =>
          prev.map((j) =>
            j.id === prog.jobId
              ? {
                  ...j,
                  progressPercent: prog.progressPercent,
                  speedBytesPerSec: prog.speedBytesPerSec,
                  etaSeconds: prog.etaSeconds,
                  downloadedBytes: prog.downloadedBytes,
                  totalBytes: prog.totalBytes,
                  status: prog.status,
                }
              : j
          )
        );
      });
    }

    return () => {
      if (unsubProgress) unsubProgress();
    };
  }, []);

  return (
    <DownloaderContext.Provider
      value={{
        queue,
        analyzedMedia,
        isAnalyzing,
        error,
        analyzeUrl,
        clearAnalyzed,
        addJob,
        addBulkJobs,
        pauseJob,
        resumeJob,
        cancelJob,
        retryJob,
        clearCompleted,
        refreshQueue,
        detectPlatform,
      }}
    >
      {children}
    </DownloaderContext.Provider>
  );
};

export const useDownloader = () => useContext(DownloaderContext);
