import { spawn, ChildProcess } from 'child_process';
import path from 'path';
import fs from 'fs';
import { BrowserWindow } from 'electron';
import { LoggerService } from './LoggerService';
import { ConfigService } from './ConfigService';
import { MediaLibraryService } from './MediaLibraryService';
import {
  PlatformType,
  MediaUrlInfo,
  MediaFormatOption,
  SubtitleTrackOption,
  DownloadJob,
  DownloadProgress,
} from '../../src/types/downloader';

export class DownloaderService {
  private static instance: DownloaderService;
  private queue: DownloadJob[] = [];
  private activeProcesses: Map<string, ChildProcess> = new Map();
  private mainWindow: BrowserWindow | null = null;
  private logger = LoggerService.getInstance();
  private configService = ConfigService.getInstance();
  private isProcessingQueue = false;

  private constructor() {}

  public static getInstance(): DownloaderService {
    if (!DownloaderService.instance) {
      DownloaderService.instance = new DownloaderService();
    }
    return DownloaderService.instance;
  }

  public setMainWindow(win: BrowserWindow | null) {
    this.mainWindow = win;
  }

  public detectPlatform(url: string): PlatformType {
    if (!url) return 'custom';
    if (/(?:youtube\.com|youtu\.be)/i.test(url)) return 'youtube';
    if (/tiktok\.com/i.test(url)) return 'tiktok';
    if (/(?:facebook\.com|fb\.watch)/i.test(url)) return 'facebook';
    if (/(?:twitter\.com|x\.com)/i.test(url)) return 'twitter';
    if (/bilibili\.com/i.test(url)) return 'bilibili';
    if (/instagram\.com/i.test(url)) return 'instagram';
    if (/vimeo\.com/i.test(url)) return 'vimeo';
    if (/twitch\.tv/i.test(url)) return 'twitch';
    return 'custom';
  }

  public async analyzeUrl(url: string): Promise<MediaUrlInfo> {
    const platform = this.detectPlatform(url);
    this.logger.info('downloader', `Analyzing URL [${platform}]: ${url}`);

    return new Promise((resolve, reject) => {
      const proc = spawn('yt-dlp', ['--dump-json', '--no-warnings', url], {
        env: { ...process.env, PYTHONIOENCODING: 'utf-8', PYTHONLEGACYWINDOWSSTDIO: '0' },
      });
      let stdoutData = '';
      let stderrData = '';

      proc.stdout.on('data', (chunk: Buffer) => {
        stdoutData += chunk.toString();
      });

      proc.stderr.on('data', (chunk: Buffer) => {
        stderrData += chunk.toString();
      });

      proc.on('close', (code: number | null) => {
        if (code !== 0 || !stdoutData.trim()) {
          this.logger.error('downloader', `Failed to analyze URL: ${stderrData}`);
          reject(new Error(stderrData.trim() || 'Failed to inspect media URL'));
          return;
        }

        try {
          const raw = JSON.parse(stdoutData.trim());
          const formats: MediaFormatOption[] = [];

          if (Array.isArray(raw.formats)) {
            for (const f of raw.formats) {
              const isVideo = f.vcodec && f.vcodec !== 'none';
              const isAudio = f.acodec && f.acodec !== 'none';
              if (isVideo || isAudio) {
                const height = f.height || 0;
                let resolutionLabel = 'Audio Only';
                if (height >= 4320) resolutionLabel = '8K (4320p)';
                else if (height >= 2160) resolutionLabel = '4K (2160p)';
                else if (height >= 1440) resolutionLabel = '2K (1440p)';
                else if (height >= 1080) resolutionLabel = 'Full HD (1080p)';
                else if (height >= 720) resolutionLabel = 'HD (720p)';
                else if (height >= 480) resolutionLabel = 'SD (480p)';
                else if (height > 0) resolutionLabel = `${height}p`;

                formats.push({
                  formatId: String(f.format_id),
                  extension: f.ext || 'mp4',
                  resolution: resolutionLabel,
                  height,
                  filesizeApproxBytes: f.filesize || f.filesize_approx || undefined,
                  vcodec: f.vcodec || 'none',
                  acodec: f.acodec || 'none',
                  fps: f.fps,
                  note: f.format_note,
                  isVideo,
                  isAudio,
                });
              }
            }
          }

          // Sort formats by height descending
          formats.sort((a, b) => b.height - a.height);

          // Subtitles
          const subtitles: SubtitleTrackOption[] = [];
          if (raw.subtitles) {
            for (const lang of Object.keys(raw.subtitles)) {
              subtitles.push({
                languageCode: lang,
                languageName: lang.toUpperCase(),
                isAutoGenerated: false,
                ext: raw.subtitles[lang]?.[0]?.ext || 'vtt',
              });
            }
          }
          if (raw.automatic_captions) {
            for (const lang of Object.keys(raw.automatic_captions)) {
              if (!subtitles.some((s) => s.languageCode === lang)) {
                subtitles.push({
                  languageCode: lang,
                  languageName: `${lang.toUpperCase()} (Auto)`,
                  isAutoGenerated: true,
                  ext: raw.automatic_captions[lang]?.[0]?.ext || 'vtt',
                });
              }
            }
          }

          const info: MediaUrlInfo = {
            url,
            platform,
            title: raw.title || 'Untitled Video',
            description: raw.description || '',
            uploader: raw.uploader || raw.channel || 'Unknown Creator',
            uploaderId: raw.uploader_id,
            durationSeconds: raw.duration || 0,
            thumbnailUrl: raw.thumbnail || undefined,
            formats,
            subtitles,
          };

          this.logger.info('downloader', `Successfully analyzed "${info.title}" by ${info.uploader}`);
          resolve(info);
        } catch (parseErr) {
          this.logger.error('downloader', 'JSON parsing error from yt-dlp', parseErr);
          reject(parseErr);
        }
      });
    });
  }

  public async addJob(options: Partial<DownloadJob>): Promise<DownloadJob> {
    const settings = this.configService.getSettings();
    const id = 'job-' + Math.random().toString(36).substring(2, 9) + '-' + Date.now();
    const platform = options.platform || this.detectPlatform(options.url || '');
    const baseDir = options.outputDirectory || settings.downloader.downloadDirectory;

    const job: DownloadJob = {
      id,
      url: options.url || '',
      platform,
      title: options.title || 'Media Download',
      uploader: options.uploader || 'Creator',
      thumbnailUrl: options.thumbnailUrl,
      selectedFormatId: options.selectedFormatId || 'best',
      selectedResolution: options.selectedResolution || settings.downloader.preferredResolution,
      includeSubtitles: options.includeSubtitles ?? settings.downloader.autoDownloadSubtitles,
      subtitleLangs: options.subtitleLangs,
      includeThumbnail: options.includeThumbnail ?? settings.downloader.autoDownloadThumbnail,
      audioOnly: options.audioOnly || false,
      outputDirectory: baseDir,
      status: 'queued',
      progressPercent: 0,
      speedBytesPerSec: 0,
      etaSeconds: 0,
      downloadedBytes: 0,
      totalBytes: 0,
      createdAt: new Date().toISOString(),
    };

    this.queue.push(job);
    this.logger.info('downloader', `Added job to download queue: "${job.title}" (${job.id})`);
    this.broadcastQueue();
    this.processQueue();

    return job;
  }

  public async addBulkJobs(urls: string[]): Promise<DownloadJob[]> {
    const created: DownloadJob[] = [];
    for (const url of urls) {
      if (url.trim()) {
        const job = await this.addJob({ url: url.trim() });
        created.push(job);
      }
    }
    return created;
  }

  public async pauseJob(id: string): Promise<boolean> {
    const proc = this.activeProcesses.get(id);
    if (proc) {
      proc.kill('SIGTERM');
      this.activeProcesses.delete(id);
    }
    const job = this.queue.find((j) => j.id === id);
    if (job && (job.status === 'downloading' || job.status === 'queued')) {
      job.status = 'paused';
      this.broadcastQueue();
      return true;
    }
    return false;
  }

  public async resumeJob(id: string): Promise<boolean> {
    const job = this.queue.find((j) => j.id === id);
    if (job && job.status === 'paused') {
      job.status = 'queued';
      this.broadcastQueue();
      this.processQueue();
      return true;
    }
    return false;
  }

  public async cancelJob(id: string): Promise<boolean> {
    const proc = this.activeProcesses.get(id);
    if (proc) {
      proc.kill('SIGTERM');
      this.activeProcesses.delete(id);
    }
    const job = this.queue.find((j) => j.id === id);
    if (job) {
      job.status = 'cancelled';
      this.broadcastQueue();
      this.processQueue();
      return true;
    }
    return false;
  }

  public async retryJob(id: string): Promise<boolean> {
    const job = this.queue.find((j) => j.id === id);
    if (job && (job.status === 'failed' || job.status === 'cancelled')) {
      job.status = 'queued';
      job.errorMessage = undefined;
      job.progressPercent = 0;
      this.broadcastQueue();
      this.processQueue();
      return true;
    }
    return false;
  }

  public clearCompleted(): boolean {
    this.queue = this.queue.filter((j) => j.status !== 'completed' && j.status !== 'cancelled');
    this.broadcastQueue();
    return true;
  }

  public getQueue(): DownloadJob[] {
    return this.queue;
  }

  private broadcastQueue() {
    if (this.mainWindow && !this.mainWindow.isDestroyed()) {
      this.mainWindow.webContents.send('download-queue-updated', this.queue);
    }
  }

  private broadcastProgress(progress: DownloadProgress) {
    if (this.mainWindow && !this.mainWindow.isDestroyed()) {
      this.mainWindow.webContents.send('download-progress', progress);
    }
  }

  private async processQueue() {
    if (this.isProcessingQueue) return;
    this.isProcessingQueue = true;

    const settings = this.configService.getSettings();
    const maxThreads = Math.min(32, Math.max(1, settings.downloader.maxConcurrentThreads || 4));

    try {
      const activeCount = this.activeProcesses.size;
      const availableSlots = maxThreads - activeCount;

      if (availableSlots > 0) {
        const queuedJobs = this.queue.filter((j) => j.status === 'queued').slice(0, availableSlots);
        for (const job of queuedJobs) {
          this.executeDownload(job);
        }
      }
    } finally {
      this.isProcessingQueue = false;
    }
  }

  private sanitizeFilename(name: string): string {
    return name.replace(/[<>:"/\\|?*]/g, '_').substring(0, 120).trim();
  }

  private executeDownload(job: DownloadJob) {
    job.status = 'downloading';
    this.broadcastQueue();

    const cleanPlatform = job.platform.charAt(0).toUpperCase() + job.platform.slice(1);
    const cleanCreator = this.sanitizeFilename(job.uploader || 'Creator');
    const cleanTitle = this.sanitizeFilename(job.title || 'Video');

    // Hierarchical Organization: Platform -> Creator -> Title
    const targetFolder = path.join(job.outputDirectory, cleanPlatform, cleanCreator, cleanTitle);
    if (!fs.existsSync(targetFolder)) {
      fs.mkdirSync(targetFolder, { recursive: true });
    }

    const outputTemplate = path.join(targetFolder, '%(title)s.%(ext)s');

    // Construct args
    const args: string[] = ['--no-warnings', '--newline', '-o', outputTemplate];

    if (job.audioOnly) {
      args.push('-x', '--audio-format', 'mp3', '--audio-quality', '0');
    } else if (job.selectedFormatId && job.selectedFormatId !== 'best') {
      args.push('-f', `${job.selectedFormatId}+bestaudio/best`);
    } else {
      args.push('-f', 'bestvideo+bestaudio/best');
    }

    if (job.includeSubtitles) {
      args.push('--write-subs', '--sub-langs', 'all', '--convert-subs', 'srt');
    }

    if (job.includeThumbnail) {
      args.push('--write-thumbnail', '--convert-thumbnails', 'jpg');
    }

    args.push(job.url);

    this.logger.info('downloader', `Spawning yt-dlp for job ${job.id}: yt-dlp ${args.join(' ')}`);

    const child = spawn('yt-dlp', args, {
      env: { ...process.env, PYTHONIOENCODING: 'utf-8', PYTHONLEGACYWINDOWSSTDIO: '0' },
    });
    this.activeProcesses.set(job.id, child);

    child.stdout.on('data', (chunk) => {
      const line = chunk.toString();
      this.parseProgressLine(job, line);
    });

    child.stderr.on('data', (chunk) => {
      const errLine = chunk.toString();
      this.logger.debug('downloader', `[yt-dlp stderr] ${errLine}`);
    });

    child.on('close', async (code) => {
      this.activeProcesses.delete(job.id);

      if (code === 0) {
        job.status = 'completed';
        job.progressPercent = 100;
        job.completedAt = new Date().toISOString();
        this.logger.info('downloader', `Job completed successfully: "${job.title}"`);

        // Find created file in target folder
        try {
          const files = fs.readdirSync(targetFolder);
          const mediaFile = files.find((f) => /\.(mp4|mkv|webm|mp3|wav|m4a)$/i.test(f));
          if (mediaFile) {
            const finalFilePath = path.join(targetFolder, mediaFile);
            job.outputFilePath = finalFilePath;

            // Auto-catalog in MediaLibraryService
            const meta = await MediaLibraryService.getInstance().probeMediaFile(finalFilePath);
            const thumbFile = files.find((f) => /\.(jpg|png|webp)$/i.test(f));
            const thumbPath = thumbFile ? path.join(targetFolder, thumbFile) : undefined;

            await MediaLibraryService.getInstance().addMedia({
              title: job.title,
              filename: mediaFile,
              filePath: finalFilePath,
              platform: job.platform,
              creator: job.uploader,
              durationSeconds: meta.duration,
              resolution: { width: meta.width, height: meta.height },
              fps: meta.fps,
              fileSizeBytes: meta.size,
              codec: meta.codec,
              audioSampleRate: meta.sampleRate,
              audioChannels: meta.channels,
              thumbnailPath: thumbPath,
              sourceUrl: job.url,
              tags: [cleanPlatform, 'Downloaded'],
              downloadJobId: job.id,
            });
          }
        } catch (err) {
          this.logger.warn('downloader', 'Failed to auto-catalog downloaded file', err);
        }
      } else {
        if (job.status !== 'paused' && job.status !== 'cancelled') {
          job.status = 'failed';
          job.errorMessage = `Download process exited with code ${code}`;
          this.logger.error('downloader', `Job failed: ${job.title} (code ${code})`);
        }
      }

      this.broadcastProgress({
        jobId: job.id,
        progressPercent: job.progressPercent,
        speedBytesPerSec: 0,
        etaSeconds: 0,
        downloadedBytes: job.downloadedBytes,
        totalBytes: job.totalBytes,
        status: job.status,
      });

      this.broadcastQueue();
      this.processQueue();
    });
  }

  private parseProgressLine(job: DownloadJob, line: string) {
    // Format: [download]  45.2% of  120.50MiB at    8.50MiB/s ETA 00:15
    const match = line.match(/\[download\]\s+([\d\.]+)%\s+of\s+~?([\d\.]+\w+)\s+at\s+([\d\.]+\w+\/s)\s+ETA\s+(\S+)/i);
    if (match) {
      const percent = parseFloat(match[1]);
      const totalStr = match[2];
      const speedStr = match[3];
      const etaStr = match[4];

      job.progressPercent = Math.min(99.9, percent);

      // Speed parsing
      const speedMatch = speedStr.match(/([\d\.]+)(\w+)\/s/i);
      if (speedMatch) {
        let speedVal = parseFloat(speedMatch[1]);
        const unit = speedMatch[2].toLowerCase();
        if (unit.startsWith('k')) speedVal *= 1024;
        else if (unit.startsWith('m')) speedVal *= 1024 * 1024;
        else if (unit.startsWith('g')) speedVal *= 1024 * 1024 * 1024;
        job.speedBytesPerSec = Math.round(speedVal);
      }

      // ETA parsing: mm:ss or hh:mm:ss
      const parts = etaStr.split(':').map((p) => parseInt(p, 10));
      if (parts.length === 2) {
        job.etaSeconds = parts[0] * 60 + parts[1];
      } else if (parts.length === 3) {
        job.etaSeconds = parts[0] * 3600 + parts[1] * 60 + parts[2];
      }

      this.broadcastProgress({
        jobId: job.id,
        progressPercent: job.progressPercent,
        speedBytesPerSec: job.speedBytesPerSec,
        etaSeconds: job.etaSeconds,
        downloadedBytes: job.downloadedBytes,
        totalBytes: job.totalBytes,
        status: job.status,
      });
    }
  }
}
